name: fitflow
description: "AI-Powered Fitness & Wellness App for office workers and college students."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase dependencies
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  
  # State management
  provider: ^6.1.1
  
  # UI components
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  lottie: ^3.3.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # AI and ML
  google_mlkit_pose_detection: ^0.14.0
  camera: ^0.11.1
  
  # Health tracking
  health: ^12.1.0
  pedometer: ^4.0.1
  
  # Utilities
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  google_generative_ai: ^0.4.6

  # In-app purchases
  in_app_purchase: ^3.1.11
  
  # Ads
  #google_mobile_ads: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
